sentry:
  dsn: https://20958c84ec248611c48807b7350d639d@o4506434535686144.ingest.sentry.io/4506434543812608
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/mydb # TODO: Change
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost # TODO: Change
    port: 6379
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  debug: true
  logging:
    level:
      org.springframework.boot.autoconfigure: DEBUG