spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/mydb # TODO: Change
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1 # TODO: Change
    port: 6379
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  logging:
    level:
      org.springframework.boot.autoconfigure: DEBUG

server:
  port: 8080